name: Build and Publish Python Package

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests targeting main

jobs:
  build:
    runs-on: ubuntu-latest  # You can change to other OS environments if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Use your preferred Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt, otherwise skip this

    - name: Install wheel and twine
      run: |
        pip install wheel twine  # Install necessary packages for building and uploading

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel  # Build the package

    - name: Upload the package to PyPI
      run: |
        twine upload dist/*  # Upload the package to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  
